/**
 * HTTP Status Codes
 * Centralized constants for HTTP status codes used throughout the application
 */

// Individual status code constants
export const HTTP_OK = 200;
export const HTTP_CREATED = 201;
export const HTTP_ACCEPTED = 202;
export const HTTP_NO_CONTENT = 204;
export const HTTP_MOVED_PERMANENTLY = 301;
export const HTTP_FOUND = 302;
export const HTTP_NOT_MODIFIED = 304;
export const HTTP_BAD_REQUEST = 400;
export const HTTP_UNAUTHORIZED = 401;
export const HTTP_FORBIDDEN = 403;
export const HTTP_NOT_FOUND = 404;
export const HTTP_METHOD_NOT_ALLOWED = 405;
export const HTTP_CONFLICT = 409;
export const HTTP_UNPROCESSABLE_ENTITY = 422;
export const HTTP_TOO_MANY_REQUESTS = 429;
export const HTTP_INTERNAL_SERVER_ERROR = 500;
export const HTTP_NOT_IMPLEMENTED = 501;
export const HTTP_BAD_GATEWAY = 502;
export const HTTP_SERVICE_UNAVAILABLE = 503;
export const HTTP_GATEWAY_TIMEOUT = 504;

// Success responses (2xx)
export const HTTP_STATUS = {
  ACCEPTED: HTTP_ACCEPTED,
  BAD_GATEWAY: HTTP_BAD_GATEWAY,
  // 4xx Client Errors
  BAD_REQUEST: HTTP_BAD_REQUEST,
  CONFLICT: HTTP_CONFLICT,

  CREATED: HTTP_CREATED,
  FORBIDDEN: HTTP_FORBIDDEN,
  FOUND: HTTP_FOUND,

  GATEWAY_TIMEOUT: HTTP_GATEWAY_TIMEOUT,
  // 5xx Server Errors
  INTERNAL_SERVER_ERROR: HTTP_INTERNAL_SERVER_ERROR,
  METHOD_NOT_ALLOWED: HTTP_METHOD_NOT_ALLOWED,
  // 3xx Redirection
  MOVED_PERMANENTLY: HTTP_MOVED_PERMANENTLY,
  NO_CONTENT: HTTP_NO_CONTENT,
  NOT_FOUND: HTTP_NOT_FOUND,
  NOT_IMPLEMENTED: HTTP_NOT_IMPLEMENTED,
  NOT_MODIFIED: HTTP_NOT_MODIFIED,

  // 2xx Success
  OK: HTTP_OK,
  SERVICE_UNAVAILABLE: HTTP_SERVICE_UNAVAILABLE,
  TOO_MANY_REQUESTS: HTTP_TOO_MANY_REQUESTS,
  UNAUTHORIZED: HTTP_UNAUTHORIZED,
  UNPROCESSABLE_ENTITY: HTTP_UNPROCESSABLE_ENTITY,
} as const;

// Type for HTTP status codes
export type HttpStatusCode = (typeof HTTP_STATUS)[keyof typeof HTTP_STATUS];
